//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillGeneration.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillRecieptItemInfo
    {
        public int BillRecieptItemId { get; set; }
        public int BillRecieptId { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ItemNo { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Mfrs { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual BillRecieptTable BillRecieptTable { get; set; }
    }
}
