//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillGeneration.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BillGenerationEntities : DbContext
    {
        public BillGenerationEntities()
            : base("name=BillGenerationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryMaster> CategoryMasters { get; set; }
        public virtual DbSet<CurrencyMaster> CurrencyMasters { get; set; }
        public virtual DbSet<RegistrationTable> RegistrationTables { get; set; }
        public virtual DbSet<TaxMaster> TaxMasters { get; set; }
        public virtual DbSet<FontMaster> FontMasters { get; set; }
        public virtual DbSet<CategoryRecieptMaster> CategoryRecieptMasters { get; set; }
        public virtual DbSet<BillRecieptTable> BillRecieptTables { get; set; }
        public virtual DbSet<BillRecieptItemInfo> BillRecieptItemInfoes { get; set; }
        public virtual DbSet<BillRecieptTaxInfo> BillRecieptTaxInfoes { get; set; }
        public virtual DbSet<SubscriptionPlan> SubscriptionPlans { get; set; }
        public virtual DbSet<SubscriptionPlanPayment> SubscriptionPlanPayments { get; set; }
    }
}
