//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillGeneration.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillRecieptTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillRecieptTable()
        {
            this.BillRecieptItemInfoes = new HashSet<BillRecieptItemInfo>();
            this.BillRecieptTaxInfoes = new HashSet<BillRecieptTaxInfo>();
        }
    
        public int BillRecieptId { get; set; }
        public int UserId { get; set; }
        public int CategoryRecieptId { get; set; }
        public int CurrencyId { get; set; }
        public int FontId { get; set; }
        public Nullable<System.DateTime> RecieptDate { get; set; }
        public string Business { get; set; }
        public string Address { get; set; }
        public string CityState { get; set; }
        public string MobileNo { get; set; }
        public string RecieptLogo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string RecieptNo { get; set; }
        public string PaymentType { get; set; }
        public string BillRecieptDynamicHtml { get; set; }
        public string Trans { get; set; }
        public string Mcc { get; set; }
        public string Auth { get; set; }
        public string ApprCode { get; set; }
        public string WebSiteName { get; set; }
        public string DocNo { get; set; }
        public string GSTNo { get; set; }
        public string BillNo { get; set; }
        public string AtndId { get; set; }
        public string FPId { get; set; }
        public string Pump { get; set; }
        public string NozlNo { get; set; }
        public string Fuel { get; set; }
        public string Density { get; set; }
        public string TinNo { get; set; }
        public string TRXId { get; set; }
        public string AccountNo { get; set; }
        public string PompaSalans { get; set; }
        public string NomarNota { get; set; }
        public string JenisBBM { get; set; }
        public string StationNo { get; set; }
        public string HelplineNo { get; set; }
        public string LandlineNo { get; set; }
        public string CINNo { get; set; }
        public string STNo { get; set; }
        public string OPNo { get; set; }
        public string TENo { get; set; }
        public string TCNo { get; set; }
        public string REFNo { get; set; }
        public string Validation { get; set; }
        public string PaymentService { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public string Lane { get; set; }
        public string Clerk { get; set; }
        public string Cashier { get; set; }
        public string MRCH { get; set; }
        public string EPSSequence { get; set; }
        public string NetworkId { get; set; }
        public string TerminalId { get; set; }
        public string SpaceNo { get; set; }
        public string TicketNo { get; set; }
        public string SNNo { get; set; }
        public string Lot_Location { get; set; }
        public string PayedAt { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public string MachName { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleType { get; set; }
        public string RegNo { get; set; }
        public string TRNNo { get; set; }
        public string CSHRNo { get; set; }
        public string STRNo { get; set; }
        public string HelpedBy { get; set; }
        public string AID { get; set; }
        public string Signature { get; set; }
        public string CVM { get; set; }
        public string StoreNo { get; set; }
        public string PharmacyNo { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Host { get; set; }
        public string FaxNo { get; set; }
        public string BillTo { get; set; }
        public string ShipTo { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerPONo { get; set; }
        public string CardEntry { get; set; }
        public string TransType { get; set; }
        public string CheckNo { get; set; }
        public string CheckId { get; set; }
        public string Tip { get; set; }
        public Nullable<System.DateTime> TaxiDate { get; set; }
        public Nullable<System.DateTime> PickupTime { get; set; }
        public Nullable<System.DateTime> DropTime { get; set; }
        public string PickupAddress { get; set; }
        public string DropAddress { get; set; }
        public string TaxiKM { get; set; }
        public string CarName { get; set; }
        public string Miles { get; set; }
        public Nullable<System.DateTime> TaxiWTTime { get; set; }
        public Nullable<decimal> BaseFare { get; set; }
        public Nullable<decimal> DistanceFare { get; set; }
        public Nullable<decimal> TimeFare { get; set; }
        public Nullable<decimal> SubCharges { get; set; }
        public Nullable<decimal> SafeRideFee { get; set; }
        public string TaxiCallNo { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<decimal> LiftLineDiscountPrice { get; set; }
        public Nullable<decimal> PromotionalPricing { get; set; }
        public string RideBy { get; set; }
        public string LicensePlate { get; set; }
        public string TollPlaza { get; set; }
        public string Operator { get; set; }
        public string Section { get; set; }
        public string VehicleStanderedWeight { get; set; }
        public string VehicleActualWeight { get; set; }
        public Nullable<decimal> OverloadedVehicleFee { get; set; }
        public string Shift { get; set; }
        public string Journey { get; set; }
        public string TCId { get; set; }
        public string BarCode { get; set; }
        public string CSH { get; set; }
        public string RelationShipNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string LandMark { get; set; }
        public string BillPeriod { get; set; }
        public Nullable<System.DateTime> BillPayDate { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<decimal> SecurityDeposit { get; set; }
        public Nullable<decimal> PreviousBalance { get; set; }
        public Nullable<decimal> Payments { get; set; }
        public Nullable<decimal> Adjustments { get; set; }
        public Nullable<decimal> LatePaymentFee { get; set; }
        public Nullable<decimal> MonthlyRentals { get; set; }
        public Nullable<decimal> UsageCharges { get; set; }
        public Nullable<decimal> OneTimeCharges { get; set; }
        public Nullable<decimal> Taxes { get; set; }
        public string ServiceTaxRegNo { get; set; }
        public string FixedlineNo { get; set; }
        public string BroadbandId { get; set; }
        public string AlternateMobileNo { get; set; }
        public string ShipToStateCode { get; set; }
        public string BillGenerateBy { get; set; }
        public string SoldBy { get; set; }
        public string SyNo { get; set; }
        public string PANNo { get; set; }
        public string InvoiceDetails { get; set; }
        public string AadharNo { get; set; }
        public string MemberShip { get; set; }
        public Nullable<decimal> UsageP_ISD_IRCalling { get; set; }
        public Nullable<decimal> UsageDataCharges { get; set; }
        public Nullable<decimal> UsageSMSCharges { get; set; }
        public Nullable<decimal> UsageVASCharges { get; set; }
        public Nullable<decimal> CurruntMonthDiscount { get; set; }
        public Nullable<decimal> BillDiscountWithTax { get; set; }
        public string BillToEmailId { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual CategoryRecieptMaster CategoryRecieptMaster { get; set; }
        public virtual CurrencyMaster CurrencyMaster { get; set; }
        public virtual FontMaster FontMaster { get; set; }
        public virtual RegistrationTable RegistrationTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillRecieptItemInfo> BillRecieptItemInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillRecieptTaxInfo> BillRecieptTaxInfoes { get; set; }
    }
}
