//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillGeneration.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillRecieptTaxInfo
    {
        public int BillRecieptTaxId { get; set; }
        public int BillRecieptId { get; set; }
        public int TaxId { get; set; }
        public Nullable<decimal> TaxInPercentage { get; set; }
    
        public virtual BillRecieptTable BillRecieptTable { get; set; }
        public virtual TaxMaster TaxMaster { get; set; }
    }
}
