//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillGeneration.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryRecieptMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryRecieptMaster()
        {
            this.BillRecieptTables = new HashSet<BillRecieptTable>();
        }
    
        public int CategoryRecieptId { get; set; }
        public int CategoryId { get; set; }
        public int FontId { get; set; }
        public string BillRecieptName { get; set; }
        public string BillRecieptDynamicHtml { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string BillRecieptSampleImage { get; set; }
        public string RecieptType { get; set; }
        public string BillRecieptPdfHtml { get; set; }
        public Nullable<bool> IsRecieptLogo { get; set; }
        public string ReceiptWidth { get; set; }
        public string ReceiptHight { get; set; }
    
        public virtual CategoryMaster CategoryMaster { get; set; }
        public virtual FontMaster FontMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillRecieptTable> BillRecieptTables { get; set; }
    }
}
