//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillGeneration.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubscriptionPlan()
        {
            this.SubscriptionPlanPayments = new HashSet<SubscriptionPlanPayment>();
        }
    
        public int SubscriptionPlanId { get; set; }
        public string SubscriptionPlan1 { get; set; }
        public string SubscriptionPlanDesc { get; set; }
        public string PaymentType { get; set; }
        public string Amount { get; set; }
        public string Color { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionPlanPayment> SubscriptionPlanPayments { get; set; }
    }
}
